format = """
$kubernetes\
$python\
$custom\
$cmd_duration\
$line_break\
$character"""

[kubernetes]
symbol = "ó±ƒ¾"
format = '[$symbol $context( \($namespace\))]($style) '
disabled = false
style = "blue"

[character]
success_symbol = "[â¯](purple)"
error_symbol = "[â¯](red)"
vimcmd_symbol = "[â®](green)"

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

[python]
symbol = "îˆµ "
format = "[$symbol$virtualenv]($style) "
style = "yellow"

[custom.rpk]
command = "rpk profile current"
symbol = "ğŸ¦Š "
when = true
style = "red"
